name: Security Check

on:
  push:
    branches: [ main, feat/*, refactor/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run security check every Monday at 9:00 UTC (17:00 Taiwan time)
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Create virtual environment
      run: uv venv
    
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install -r requirements-dev.txt
    
    - name: Run bandit security linter
      run: |
        source .venv/bin/activate
        bandit -c .bandit -r main.py secure_input.py -f json -o bandit-report.json || true
        bandit -c .bandit -r main.py secure_input.py || true
    
    - name: Run safety check
      run: |
        source .venv/bin/activate
        safety scan --json --output safety-report.json || true
